import { AutoGenerateds } from "@/src/shared/entities/AutoGenerateds"
import { Company } from "../entities/Company"

export abstract class CompanyRepository {
  public abstract add(
    payload: Omit<Company, keyof AutoGenerateds>
  ): Promise<Company>
  public abstract get(id: number): Promise<Company>
  public abstract save(company: Company): Promise<void>
}
